name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd caminho/para/seu/diretorio
          npm install

      - name: Build project
        run: |
          cd caminho/para/seu/diretorio
          npm run build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages

      - name: Set output example
        run: echo "variable_name=value" >> $GITHUB_ENV
