name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          artifact_name: github-pages
          preview: false

      - name: Set output example
        run: echo "variable_name=value" >> $GITHUB_ENV
        
Atualizar workflow para deploy no GitHyb Pages
